workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: linux  # 또는 mac_mini
    environment:
      flutter: stable
      vars:
        PROJECT_DIR: "."  # 👈 루트 디렉토리를 현재로 명시
    scripts:
      - cd $PROJECT_DIR
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
