workflows:
  flutter-build:
    name: Basic Flutter Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
