workflows:
  flutter-build:
    name: Flutter Build in Subfolder
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - cd my_flutter_project
      - flutter pub get --directory my_flutter_project
      - flutter build apk --release --target-directory my_flutter_project

    artifacts:
      - my_flutter_project/build/app/outputs/flutter-apk/app-release.apk
