workflows:
  flutter-build:
    name: Flutter Build for Android and iOS
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
